name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write
  pull-requests: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Go mod tidy
        run: go mod tidy
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ github.ref_type == 'branch' && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
